# current machine's name, optional; it can be used to filter settings or in the commit message
hostname: ""
# more details at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/hostname.md

# selected profile, required
profile: main
# repository to sync the settings with, required
repository:
  # repository's type, required (dummy: no sync)
  type: dummy


# # how to run commands before and after events at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/hooks.md
# hooks:
#   post-upload: osascript -e 'display notification "The settings have been uploaded"'


# # sync on local file system
# repository:
#   type: file
#   # path of the local directory to sync with, required
#   path: ~/Development/settings


# # sync on local git
# repository:
#   type: git
#   # path of the local git repository to sync with, required
#   path: ~/Development/settings
#   # branch to sync on, optional (set to `master` by default)
#   branch: master
#   # how to personalize the commit messages at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/commit-messages.md


# # sync on remote git
# repository:
#   type: git
#   # url of the remote git repository to sync with, required
#   url: git@github.com:username/settings.git
#   # branch to sync on, optional (set to `master` by default)
#   branch: master
#   # how to personalize the commit messages at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/commit-messages.md


# # sync on remote directory with rsync
# repository:
#   type: rsync
#   # url of the remote directory to sync with, required
#   url: server:~/settings
#   # shell used by rsync, optional (set to `ssh` by default)
#   shell: ssh


# # sync on remote directory with webdav
# repository:
#   type: webdav
#   # url of the remote directory, required
#   url: http://localhost:9988/webdav/server
#   # the username, optional
#   username: webdav-user
#   # the password, optional
#   password: pa$$w0rd!
#   # all options available at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/webdav.md
